import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Ai doc ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="max-w-[1300px] mx-auto px-3">{children}</main>
      </body>
    </html>
  );
}
